#!/usr/bin/env bash
# ------------------------------------------------------------------------------------------------
# Nursing App Development
# ------------------------------------------------------------------------------------------------
alias tdir='cd $HOME/vagrant-local/www/mayo-nursing/htdocs/wp-content/themes/nursing-theme'
alias pdir='cd $HOME/vagrant-local/www/mayo-nursing/htdocs/wp-content/mu-plugins'
alias vdir='cd $HOME/VVV'
alias vssh='vdir && vagrant ssh'
# ----------------------------------------------------------------------------------
# Directory Helpers
# ----------------------------------------------------------------------------------
alias grep='grep --color=auto'
alias qfind="find . -name "
alias cp='cp -iv'
alias mv='mv -iv'
alias mkdir='mkdir -pv'
alias l='ls -FGlAhp'
alias less='less -FSRXc'
alias ..='cd ../'
alias ...='cd ../..'
alias ~='$HOME'
alias c='clear'
alias which='type -all'
alias path='echo -e ${PATH//:/\\n}'
alias lr='ls -R | grep ":$" | sed -e '\''s/:$//'\'' -e '\''s/[^-][^\/]*\//--/g'\'' -e '\''s/^/   /'\'' -e '\''s/-/|/'\'' | less'
alias ytdlmp3='youtube-dl --extract-audio --audio-format mp3'
alias mountpriv="sudo mount -t nfs spi:/srv/nfs/priv /Users/m030006/nfs/priv"
alias umountpriv="sudo umount -t nfs spi:/srv/nfs/priv /Users/m030006/nfs/priv"
